In [ ]:
import numpy as np

In [ ]:
a=np.array([[1,2,3],[4,5,6]])
print(a)

[[1 2 3]
 [4 5 6]]


In [ ]:
print(a.ravel())

[1 2 3 4 5 6]


In [ ]:
print(a.T)

[[1 4]
 [2 5]
 [3 6]]


In [ ]:
a=np.array([[5,4,3],[2,1,9]])
print(a)

[[5 4 3]
 [2 1 9]]


In [ ]:
b=np.sort(a,axis=1)
print(b)

[[3 4 5]
 [1 2 9]]


Write a numpy program to generate six random integers between 10 and 30

In [ ]:


# Generate six random integers between 10 and 30
random_numbers = np.random.randint(10, 31, size=6)

# Print the random numbers
print(random_numbers)

[12 11 17 10 13 26]


Write a numpy program to create a 3x3 array with random values and find the minimum and maximum values

In [ ]:
# Create a 3x3 array with random values
array = np.random.randint(10, 31, size=(3, 3))
print(array)
# Find the minimum and maximum values

# Print the minimum and maximum values
print("The minimum value is:",np.min(array))
print("The maximum value is:",np.max(array))

[[24 10 21]
 [27 29 28]
 [20 10 12]]
The minimum value is: 10
The maximum value is: 29


11/09/23 Getting Started with Pandas

In [ ]:
import pandas as pd
data=[1,2,3,4,5]
df=pd.DataFrame(data)
print(df)

   0
0  1
1  2
2  3
3  4
4  5


In [ ]:
data=(1,2,3,4,5)
df=pd.DataFrame(data)
print(df)

   0
0  1
1  2
2  3
3  4
4  5


In [ ]:
data=[['Alex',10],['Bob',12],['Clarke',13]]
df=pd.DataFrame(data,columns=['Name','Age'])
print(df)

     Name  Age
0    Alex   10
1     Bob   12
2  Clarke   13


In [ ]:
data=[['Alex',10,101],['Bob',12,102],['Clarke',13,103]]
df=pd.DataFrame(data,columns=['Name','Age','Student id'])
print(df)

     Name  Age  Student id
0    Alex   10         101
1     Bob   12         102
2  Clarke   13         103


In [ ]:
data={'Name':['Tom','Jack','Steve','Ricky'],'Age':[28,34,29,42]}
df=pd.DataFrame(data)
print(df)

    Name  Age
0    Tom   28
1   Jack   34
2  Steve   29
3  Ricky   42


In [ ]:
data={'Name':['Tom','Jack','Steve','Ricky'],'Age':[28,34,29,42]}
df=pd.DataFrame(data,index=['rank1','rank2','rank3','rank4'])
print(df)

        Name  Age
rank1    Tom   28
rank2   Jack   34
rank3  Steve   29
rank4  Ricky   42


In [ ]:
data=[{'a':1,'b':2},{'a':5,'b':10,'c':20}]
df=pd.DataFrame(data)
print(df)

   a   b     c
0  1   2   NaN
1  5  10  20.0


In [ ]:
data=[{'a':1,'b':2},{'a':5,'b':10,'c':20}]
df=pd.DataFrame(data,index=['first','second'])
print(df)

        a   b     c
first   1   2   NaN
second  5  10  20.0


write a program tocreate Datframe to loist of dataframe with list of dictionaries ,row indices and colum indicies

In [ ]:
data=[{'a':1,'b':2},{'a':5,'b':10,'c':20}]
df=pd.DataFrame(data,index=['first','second'],columns=['a','b'])
print(df)

        a   b
first   1   2
second  5  10


In [ ]:
print('Adding a new column by passing as Series: ')
df['three']=pd.Series([10,20,30],index=['a','b','c'])
print(df)

print('Adding a new column using the exisiting columns in DataFrame: ')
df['four']=df['one']+df['three']

print(df)


Adding a new column by passing as Series: 
        a   b  three
first   1   2    NaN
second  5  10    NaN
Adding a new column using the exisiting columns in DataFrame: 


KeyError: ignored

In [ ]:
d={'one':pd.Series([1,2,3],index=['a',])}

Write A ProGRAM to create and extract the rows strating from 2 to 5

In [ ]:
import pandas as pd

# Create a list of data
data = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

# Create a DataFrame
df = pd.DataFrame(data, columns=['Number'])

# Print the original DataFrame
print('Original DataFrame:')
print(df)

# Extract the rows starting from 2 to 5
df_filtered = df[2:5]

# Print the DataFrame after extracting the rows
print('DataFrame after extracting rows starting from 2 to 5:')
print(df_filtered)


Original DataFrame:
   Number
0       1
1       2
2       3
3       4
4       5
5       6
6       7
7       8
8       9
9      10
DataFrame after extracting rows starting from 2 to 5:
   Number
2       3
3       4
4       5


Write a program to delete a row in dataframe in row dataframe

In [ ]:
import pandas as pd

# Create a DataFrame
df = pd.DataFrame({'Name': ['John', 'Jane', 'Peter', 'Mary'], 'Age': [20, 21, 22, 23]})

# Print the original DataFrame
print('Original DataFrame:')
print(df)

# Delete the row with index 2
df = df.drop(2)

# Print the DataFrame after deleting the row
print('DataFrame after deleting row with index 2:')
print(df)


Original DataFrame:
    Name  Age
0   John   20
1   Jane   21
2  Peter   22
3   Mary   23
DataFrame after deleting row with index 2:
   Name  Age
0  John   20
1  Jane   21
3  Mary   23
